### ISSUE TITLE
Should go back to prior brightness setting and NOT to 100%.

### ISSUE THREAD

**Issue by careca1970** [nailfarmer/gnome-shell-dim-on-battery-extension#1]
After going to battery power, and adjusting brightness to the value set in the extension settings, when returning to AC-power, it should go back to prior setting, and NOT to full (100%) brightness.
Many people doesn't use their monitor at 100% brightness.

Many thanks for your extension. It will be a hit in short time. Just some improvements needed!
BR

**Comment by nailfarmer** [comment]
Thanks for the suggestion, and for trying out this extension! Saving brightness levels should be mostly resolved with the latest commits.  I'm not sure how to canonically detect changes to brightness level in glib right now, but we can at least save the brightness settings when we change state from AC to battery and back again. There may be edge cases where it fails and you'll have to manually set the ac and battery brightness levels through the preferences dialog; can you please open a new issue if you find one of these edge cases?
