### ISSUE TITLE
"UPower is undefined" in Gnome Shell 42.5

### ISSUE THREAD

**Issue by davidmegginson** [nailfarmer/gnome-shell-dim-on-battery-extension#16]
Using Ubuntu 22.04 and a manual install from GitHub.

**Comment by davidmegginson** [comment]
The solution here works for me in Ubuntu 22.04 and Gnome Shell 42.5:

https://gitlab.com/nailfarmer/gnome-shell-dim-on-battery-extension/-/issues/17

**Comment by nailfarmer** [comment]
Thanks for reporting! This bug should be fixed in master and should be approved on the extensions site shortly.
