### ISSUE TITLE
brightness settings corrupted quite often

### ISSUE THREAD

**Issue by killarny** [nailfarmer/gnome-shell-dim-on-battery-extension#2]
I'm using Ubuntu 15.04, with Gnome 3.16.3, and it seems like every time I reboot my laptop, the settings for this extension are set to random values. I'll open up Tweak Tool and change them (to 20% on battery, 100% on AC) and then the extension will work like a dream until I reboot again. For example. when I booted this morning, it was set to 18% on battery, 0% on AC.

**Comment by killarny** [comment]
I just logged out instead of rebooting, and the values became corrupted. (They were set to 20/100 prior to logout, and corrupted to 20/0 after logging in again.)

**Comment by killarny** [comment]
Booted the laptop today, and the extension values were set to 100/100 - just noting that the values seem to be able to increase from what they're set to, in addition to decreasing.

**Comment by nailfarmer** [comment]
Thanks so much for the detailed report. Can you see if the latest commits solve the corruption issue?

**Comment by killarny** [comment]
I'm still seeing settings corruption, although it feels like the behavior for it is different somehow. I'll do more testing and see if I can report better.

There seems to be a new issue now, that I assume is introduced by your attempted fixes.. the brightness doesn't change at all when I plug/unplug the AC. However, if I have the extension settings open, then I unplug AC, and fiddle with the settings (ie, hit the up and down arrows on the battery setting value), it'll then detect the unplugging and change the brightness.

**Comment by nailfarmer** [comment]
Gah. My apologies, do you mind trying the latest? I somehow typo-ed in between testing and committing.  Cheers!

**Comment by killarny** [comment]
Sorry for leaving this unclosed.. this issue seems to have been fixed. I haven't experienced any more problems! Thank you!
