### ISSUE TITLE
Screen brightness value not persistent

### ISSUE THREAD

**Issue by rizkytahara** [nailfarmer/gnome-shell-dim-on-battery-extension#5]
Using Fedora 22, the screen brightness value did not have a persistent value with the value that I already input at the settings dialog. For example; I've set the value to 20 on battery and 40 on AC power, after resume from suspend, the value got lower than the settings. I haven't tried for the hibernate; Any solution how to make it persistent?

**Comment by nailfarmer** [comment]
Thanks so much for spotting this!  It sounds like there might be some cumulative rounding errors occurring.  I will look in to it.

**Comment by rizkytahara** [comment]
any update yet?

**Comment by nailfarmer** [comment]
Latest commit should fix this. Please reopen if you still encounter this!

**Comment by rizkytahara** [comment]
thank you, it works.. should it be updated to the gnome extensions too?

**Comment by nailfarmer** [comment]
Yes, the fix should be available on gnome extensions now, as well :-)
