### ISSUE TITLE
Does not work on GNOME 3.24

### ISSUE THREAD

**Issue by ocludo** [nailfarmer/gnome-shell-dim-on-battery-extension#8]
The extension has stopped working on GNOME (Shell) 3.24. Adding 3.24 to metadata.json and/or disabling extension version validation does not help. The extension is available in GNOME Tweak Tool, for example, but nothing happens and the brightness remains unaltered whether the power is plugged in or disconnected.

**Comment by Forger125** [comment]
I can replicate this problem on Ubuntu 17.04 running GNOME 3.24. Disabling/re-enabling, changing settings, and uninstall/reinstall did not stop the problem either, in addition to the tweaks tried by @ocludo.

**Comment by ocludo** [comment]
This may be happening because the org.gnome.SettingsDaemon D-Bus service is no longer available in GNOME 3.24.

**Comment by Th3Z0ne** [comment]
I am also affected by this which is bad, as its an essential for a laptop in my mind.

**Comment by Th3Z0ne** [comment]
Hello - been a bit digging around the web and in the arch wiki I found the following command 
`gdbus call --session --dest org.gnome.SettingsDaemon.Power --object-path /org/gnome/SettingsDaemon/Power --method org.freedesktop.DBus.Properties.Set org.gnome.SettingsDaemon.Power.Screen Brightness "<int32 50>"` which when issued in terminal will set the screen to 50% of its brightness.

I do not understand how this differs from the lines used in this extension:
`const BUS_NAME = 'org.gnome.SettingsDaemon';`
and 
`const OBJECT_PATH = '/org/gnome/SettingsDaemon/Power';`

Does any of you know how to implement that working command?

**Comment by Th3Z0ne** [comment]
I have found the problem - issued a pull request. #10 for me it works, feel free to test it please.

**Comment by nailfarmer** [comment]
@Th3Z0ne thank you for your contributions! Merged and fixed in master, I'll push these changes to the extension site shortly.

**Comment by Th3Z0ne** [comment]
@nailfarmer thank you for merging - I am realy happy that I was able to figure it out.

**Comment by Th3Z0ne** [comment]
just cloned your repo again - with the check if its above 3.24.2 its not working for me.

**Comment by nailfarmer** [comment]
Thanks @Th3Z0ne! I've pushed another change that seems to fix it for me, can you test?

**Comment by Th3Z0ne** [comment]
Can confirm it works! 

Thank's a lot for your work! Can not say it often enough - essential extension for anyone with a laptop.

**Comment by nailfarmer** [comment]
Cheers!  I really appreciate you solving this issue and performing the additional testing.
